import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { findExperimentsDir, listExperimentDirs, listRunDirs, listVerdictFiles } from '../tree.js'
import { parseFrontmatter } from '../frontmatter.js'

export function index(args) {
  const experimentsDir = findExperimentsDir(args[0])
  const lines = ['# experiments', '', 'Regenerated by `aladdin index` — do not edit by hand.', '']
  for (const expDir of listExperimentDirs(experimentsDir)) {
    const name = path.basename(expDir)
    const expFile = path.join(expDir, 'experiment.md')
    if (!existsSync(expFile)) continue
    let data
    try {
      ;({ data } = parseFrontmatter(readFileSync(expFile, 'utf8'), expFile))
    } catch {
      lines.push(`- **${name}** — BROKEN experiment.md, run \`aladdin check\``)
      continue
    }
    const runs = listRunDirs(expDir).length
    const verdicts = listVerdictFiles(expDir).length
    const n = (data.scenes ?? []).length
    const summary = data.status === 'concluded' ? data.conclusion : data.question
    lines.push(`- **${name}** — ${data.status} — ${summary} (n=${n}, ${runs} runs, ${verdicts} verdicts)`)
  }
  if (lines.length === 4) lines.push('(no experiments yet)')
  writeFileSync(path.join(experimentsDir, 'INDEX.md'), lines.join('\n') + '\n')
  console.log(`wrote ${path.join(experimentsDir, 'INDEX.md')}`)
}
